name: build

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/*.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: go build -v -o pcc cmd/pcc/**
      - name: Run tests
        run: go test -v ./...
